#include "lift_controller.h"
#include <cmath>
namespace esphome::living_room::lr {
void LiftController::configure(LiftConfig cfg) { cfg.top_position_pulses = std::max<int32_t>(1, cfg.top_position_pulses); cfg.slow_zone_pulses = std::max<int32_t>(0, cfg.slow_zone_pulses); cfg_ = cfg; }
void LiftController::restore(int32_t pos, bool homed, bool unsafe) { position_pulses_ = std::clamp(pos, int32_t{0}, cfg_.top_position_pulses); homed_ = homed && !unsafe; if (unsafe) { state_ = LiftState::Fault; fault_code_ = FaultCode::NeedsReference; } else { state_ = LiftState::Idle; fault_code_ = FaultCode::None; } persistence_dirty_ = false; }
void LiftController::command_open() { if (!faulted()) start_move_to(cfg_.top_position_pulses); }
void LiftController::command_close() { if (faulted()) return; if (!homed_) { command_reference(); return; } start_move_to(0); }
void LiftController::command_set_position(float p) { if (faulted()) return; if (!homed_) { set_fault(FaultCode::NeedsReference); return; } const auto c = std::clamp(p, 0.0f, 1.0f); start_move_to(static_cast<int32_t>(std::lround(c * cfg_.top_position_pulses))); }
void LiftController::command_stop() { if (is_moving()) stop_clean(); }
void LiftController::command_reference() { if (faulted() && fault_code_ != FaultCode::NeedsReference) return; state_ = LiftState::HomingDown; target_pulses_ = 0; move_start_ms_ = 0; persistence_dirty_ = true; }
void LiftController::command_clear_fault() { state_ = LiftState::Idle; fault_code_ = FaultCode::None; persistence_dirty_ = true; }
void LiftController::on_encoder_delta(int delta) { if (state_ == LiftState::MovingUp) position_pulses_ += std::abs(delta); else if (state_ == LiftState::MovingDown || state_ == LiftState::HomingDown) position_pulses_ -= std::abs(delta); else return; position_pulses_ = std::clamp(position_pulses_, int32_t{0}, cfg_.top_position_pulses); }
MotorCommand LiftController::tick(const TickInputs &in) { persistence_dirty_ = false; if (move_start_ms_ == 0 && is_moving()) { move_start_ms_ = in.now_ms; last_encoder_ms_ = in.now_ms; persistence_dirty_ = true; } if (in.bottom_endstop) { position_pulses_ = 0; if (state_ == LiftState::HomingDown || state_ == LiftState::MovingDown) { homed_ = true; stop_clean(); return {}; } } if (in.top_endstop) { position_pulses_ = cfg_.top_position_pulses; if (state_ == LiftState::MovingUp) { homed_ = true; stop_clean(); return {}; } } if (is_moving()) { if ((in.now_ms - move_start_ms_) > cfg_.max_move_ms) { set_fault(FaultCode::Timeout); return {}; } if (target_reached()) { stop_clean(); return {}; } } switch (state_) { case LiftState::MovingUp: return {Direction::Up, ramped_duty(in.now_ms, cfg_.cruise_duty_up)}; case LiftState::MovingDown: return {Direction::Down, ramped_duty(in.now_ms, cfg_.cruise_duty_down)}; case LiftState::HomingDown: return {Direction::Down, cfg_.homing_duty}; default: return {}; } }
float LiftController::position_percent() const { return std::clamp(100.0f * static_cast<float>(position_pulses_) / static_cast<float>(cfg_.top_position_pulses), 0.0f, 100.0f); }
bool LiftController::is_moving() const { return state_ == LiftState::MovingUp || state_ == LiftState::MovingDown || state_ == LiftState::HomingDown; }
void LiftController::start_move_to(int32_t target) { target_pulses_ = std::clamp(target, int32_t{0}, cfg_.top_position_pulses); if (target_pulses_ == position_pulses_) { stop_clean(); return; } state_ = target_pulses_ > position_pulses_ ? LiftState::MovingUp : LiftState::MovingDown; move_start_ms_ = 0; persistence_dirty_ = true; }
void LiftController::set_fault(FaultCode code) { state_ = LiftState::Fault; fault_code_ = code; persistence_dirty_ = true; }
void LiftController::stop_clean() { state_ = LiftState::Idle; fault_code_ = FaultCode::None; move_start_ms_ = 0; persistence_dirty_ = true; }
float LiftController::ramped_duty(uint32_t now_ms, float cruise_duty) const { if (cfg_.ramp_ms == 0 || move_start_ms_ == 0) return cruise_duty; const float t = std::clamp(static_cast<float>(now_ms - move_start_ms_) / static_cast<float>(cfg_.ramp_ms), 0.0f, 1.0f); const float min_duty = 0.20f; const float ramped = min_duty + (cruise_duty - min_duty) * t; const int32_t remaining = std::abs(target_pulses_ - position_pulses_); if (remaining <= cfg_.slow_zone_pulses && cfg_.slow_zone_pulses > 0) { const float slow = std::clamp(static_cast<float>(remaining) / static_cast<float>(cfg_.slow_zone_pulses), 0.25f, 1.0f); return std::max(min_duty, ramped * slow); } return ramped; }
bool LiftController::target_reached() const { if (state_ == LiftState::MovingUp) return position_pulses_ >= target_pulses_; if (state_ == LiftState::MovingDown) return position_pulses_ <= target_pulses_; return false; }
}  // namespace esphome::living_room::lr
